# Change these first
owner: rikrdo1979 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Natural
    url: https://www.mercadodevida.es
  - name: comerecologico.com
    url: https://www.comerecologico.com
  - name: rikrdo.es
    url: https://www.rikrdo.es/cv
  - name: Lugar de la Luz
    url: https://www.lugardelaluz.es/guests
  - name: Terapia Visual
    url: https://www.terapiavisualsanpedrodealcantara.com
  - name: Nextcloud Pi
    url: https://ftprikrdo.duckdns.org
  - name: Gitea
    url: http://gitrikrdo.duckdns.org:3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: github.com/rikrdo1979/upptime
  baseUrl: /upptime
  theme: light
  logoUrl: https://rikrdo.es/images/logo-re.svg
  name: ""
  #introTitle: "**Upptime** by GitHub."
  #introMessage: "Sites Monitoring - **rikrdo.es**"
  #introTitle: "*rikrdo.es** sites monitoring"
  favicon: https://rikrdo.es/images/logo-re.png
  faviconSvg: https://rikrdo.es/images/logo-re.svg
  navbar:
    - title: Info
      href: https://www.rikrdo.es/cv
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
